# Generated by Django 6.0.3 on 2026-03-12 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='reason',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='check_in_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='accommodation.userprofile'),
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.userprofile'),
        ),
        migrations.CreateModel(
            name='RoomInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('fixed', 'Fixed')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.userprofile')),
            ],
        ),
    ]
