# Generated by Django 6.0.3 on 2026-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_checkoutrequest_comments_checkoutrequest_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fixed', 'Fixed')], default='submitted', max_length=20),
        ),
    ]
