# Generated by Django 6.0.3 on 2026-03-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_alter_roominspection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutrequest',
            name='check_in_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accommodation.checkinrecord'),
        ),
        migrations.AlterField(
            model_name='roominspection',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('fixed', 'Fixed')], default='submitted', max_length=20),
        ),
    ]
