# Generated by Django 6.0.3 on 2026-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_alter_checkoutrequest_check_in_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrequest',
            name='room_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='roominspection',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('fixed', 'Fixed'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
    ]
