# Generated by Django 6.0.3 on 2026-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_checkoutrequest_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutrequest',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
