# Generated by Django 6.0.3 on 2026-03-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_alter_checkoutrequest_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked Out')], default='active', max_length=20),
        ),
    ]
