# Generated by Django 6.0.3 on 2026-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_checkinrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominspection',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
