# Generated by Django 6.0.3 on 2026-03-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_roominspection_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='accommodation.userprofile'),
        ),
    ]
