# Generated by Django 6.0.3 on 2026-03-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0009_alter_checkinrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominspection',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('fixing', 'Fixing'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
    ]
